### ISSUE TITLE
PowerView - Get-NetLocalGroup Recursion

### ISSUE THREAD

**Issue by Meatballs1** [PowerShellMafia/PowerSploit#153]
The Recursion mechanism in `Get-NetLocalGroup` only occurs if the group is a domain group. However we could have a domain group, within a local group, within a local group etc, so we need to recurse for all group types? 

Additionally I think the WinNT and API routes are just different local method functions to the same network traffic?

**Comment by Meatballs1** [comment]
It looks each technique struggles to differentiate between local groups and local users. Maybe need to perform NetLocalGroupEnum to list the groups first and recurse if the group member is a a local group...

**Comment by HarmJ0y** [comment]
I believe that the WinNT provider returns a COM object that lets you pull additional information out (description, last logon time, etc etc etc). The [LOCALGROUP_MEMBERS_INFO*](https://msdn.microsoft.com/en-us/library/windows/desktop/aa370601(v=vs.85).aspx) structures have limited information, with [LOCALGROUP_MEMBERS_INFO_2](https://msdn.microsoft.com/en-us/library/windows/desktop/aa370280(v=vs.85).aspx) being the one that returns the most information. Since it doesn't tell you if the member is local or not, my approach was to check the *-500 account to extract the machine SID, and use that to determine if the results were local or domain: https://github.com/PowerShellMafia/PowerSploit/blob/4b40e8609c75b00a6ccbf58fc121882975854f59/Recon/PowerView.ps1#L7750-L7760

This is obviously not ideal, and fails when you enumerate against the primary DC for a particular domain (lists all as local). And as I understand it, local groups can not be nested ([according to Microsoft at least](https://technet.microsoft.com/en-us/library/ee681621(v=ws.10).aspx)), so the only results we might get are local users added to a local group- could use NetUserEnum to deconflict possibly...

**Comment by Meatballs1** [comment]
Ah you defnitely can do get it to be done, but looks like permission wise it doesn't work:

`Additionally, the command line tool net.exe permits creating a nested local group structure via the net localgroup syntax, the functionality of the nested group membership does not work. The user token only reflects the direct local group that the user is added to as a member. The token will not list the nested local group and the user can not access any resource which has been granted permission to the nested local group.`

**Comment by HarmJ0y** [comment]
Yep, I didn't know until I was corrected on Twitter after the GPO correlation post :)

**Comment by HarmJ0y** [comment]
With landing your commit, I'm closing this issue.
