### ISSUE TITLE
Powerview Get-NetlocalGroup type problem with PS 5.1

### ISSUE THREAD

**Issue by dwaynecyr** [PowerShellMafia/PowerSploit#177]
Get-netlocalgroup generates an error in Powershell 5.1:
WARNING: [!] Error: Error while invoking GetType. Could not find member.

This is probably the same problem detailed here (with a workaround)
http://stackoverflow.com/questions/31949541/print-local-group-members-in-powershell-5-0 

with the gettype statements on line 7803 and 7804.

**Comment by HarmJ0y** [comment]
We are aware of this issue, and will have it fixed in the revamp that's being pushed out in a few days.

**Comment by HarmJ0y** [comment]
This should hopefully be fixed in the dev branch as of https://github.com/PowerShellMafia/PowerSploit/commit/7c32bf69f334b7c15c644cdb41188bdfe1a0b0e8 , if it's still an issue feel free to reopen. The new function is **Get-NetLocalGroupMember**, defaulting to API access but '-Method winnt' will force the WinNT method that was previously broken.
