### ISSUE TITLE
Invoke-wmicommand runtime error

### ISSUE THREAD

**Issue by kureeoffsec** [PowerShellMafia/PowerSploit#218]
When running against a remote 2008, I get a runtime error with the dev version of invoke-wmicommand.  

Command run:
invoke-wmicommand -payload { echo 'hello!' > c:\temp\hello.txt } -computername <ip address> -credential $cred -enableallprivileges -verbose

output:
creating the following registry key:
HKEY_CURRENT_USER\Software\Microsoft\Cryptography\RNG
validating read/write/delete privileges for the following registry key:
HKEY_CURRENT_USER\Software\Microsoft\Cryptography\RNG
Full PowerShellpath:
c:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Storing the payload into the following registry value:
HKEY_CURRENT_USER\Software\Microsoft\Cryptography\RNG\Seed
Payload successfully executed from:
HKEY_CURRENT_USER\Software\Microsoft\Cryptography\RNG\Seed

Error:
Unable to retrieve the payload results from the following registry value:
HKEY_CURRENT_USER\Software\Microsoft\Cryptography\RNG\Value
at line:332 char:17
throw "[$computer] Unable to retrieve the payload results from the ...

**Comment by kureeoffsec** [comment]
![clean_error](https://cloud.githubusercontent.com/assets/16323173/22652245/bd1b3e70-ec53-11e6-9623-41dd1e543b83.png)

I know that $userCredential is correct because I am able to establish a connection to the C$ share of $Server with it.

**Comment by mattifestation** [comment]
I don't have enough information to debug this. Can you help me out a bit?

1) Did you confirm that C:\temp\low\test.txt was created?
2) Did you try Invoke-WmiCommand locally with the same payload?
3) Did you try issuing a command that actually returns output? Piping text to test.txt doesn't return output.
4) Issue a command that returns output and validate that the registry values are actually populated with both the command and the command result.

In your case, considering the exception being thrown, `HKCU\SOFTWARE\Microsoft\Cryptography\RNG\Value` is not being written to which is why the GetStringValue method isn't returning anything. One suggestion might be to adjust `Start-Sleep -Seconds 5` to a higher delay in case the spawned PowerShell hasn't taken enough time to finish execution.

**Comment by kureeoffsec** [comment]
1) The file is not being created.  
2) Unfortunately I don't have local access to the box, so I have not been able to attempt to try this locally.  I have access to the C$ share, and that way can test output.  

I'll try changing the sleep time to 30 and get back to you.

**Comment by kureeoffsec** [comment]
I made the 30 second change the script, and same result, so I think it is fair to rule out delay time in issues with the script.

**Comment by mattifestation** [comment]
If you're not able to confirm that it works locally and on a remote machine that you control, unfortunately, I wouldn't be able to determine what the issue might be. I'm not able to reproduce the issue on my side. Ultimately, for some reason, the payload result value is not being written to. Did you try specifying a non-default value name?

**Comment by kureeoffsec** [comment]
I did give that a shot.  The script performs the same actions, thinking it has passed the access checks.

**Comment by mattifestation** [comment]
So it works when you run it locally, yeah?

**Comment by kureeoffsec** [comment]
I unfortunately cannot test is locally.

**Comment by mattifestation** [comment]
Roger. Sorry I can't be of any help then.

**Comment by kureeoffsec** [comment]
Finally got a chance to dig into the box in question.  Powershell 1.0 was the only version installed and was causing a lot of errors aside from just the script in question.
