### ISSUE TITLE
Add-Persistence : Cannot process argument transformation on parameter 'ScriptBlock'.

### ISSUE THREAD

**Issue by pawp81** [PowerShellMafia/PowerSploit#324]
In what type should ScriptBlock be provided? How to prepare the script for adding persistence to it? When I refer to powershell script by calling -ScriptBlock parameter I get following error:
Add-Persistence -ScriptBlock .\get-process.ps1 -UserPersistenceOption $elevatedOptions -verbose
Add-Persistence : Cannot process argument transformation on parameter 'ScriptBlock'. Cannot convert the ".\getprocess.ps1" value of type "System.String" to type "System.Management.Automation.ScriptBlock"

getprocess.ps1 has single instruction: get-process.

**Comment by toomuchmunsch** [comment]
The week in breaches is a newsletter that keeps you informed about the latest data breaches and cybersecurity news.

the week in breaches


Subscribe (https://www.upguard.com/blog/subscribe?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )


twitter (https://www.twitter.com/UpGuard?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

linkedin (https://www.linkedin.com/company/upguard/?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

facebook (https://www.facebook.com/UpGuard?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Wednesday

April 24, 2019

Hi there,

Thank you for reading the latest issue of the week in breaches! This is a newsletter that surfaces the week's latest data breaches and cybersecurity news.

We're always keen to get your feedback. Send us an email with your thoughts, or if there are specific topics you’d like to learn more about.

THIS WEEK

Class Action Defense Costs Rising; Wave of Cyber Actions Predicted (https://www.insurancejournal.com/news/national/2019/04/22/524334.htm?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Insurance Journal | 🇺🇸 USA l April 22, 2019

The overall cost to large businesses of defending against class action lawsuits continues to rise even as the number of companies sued falls. This is happening because more companies being sued are facing multiple suits and the cases have become more complex and high risk.

The recently released Carlton Fields Class Action Survey tells an interesting story about how attorneys view cyber risk and what their companies are doing about it relative to other types of litigation. On one hand, 54% of those surveyed "believe data privacy and security will be the next wave of class actions." That contrasts with their current state of only 0.2% of their annual spend going toward data privacy issues now. (An additional 3.6% of current spend goes toward tech statute violations, which, from a technologist perspective, often have similar root causes).

Data privacy ranks last in the fields where they report on current spend, and yet is the top ranked upcoming concern for class action suits. If the attorneys surveyed are correct, that means that we may still be in the calm before the storm that was predicted to follow GDPR. Indeed, the legislation that has commanded more attention is the California Consumer Privacy Act. The costs of data leaks and breaches have thus far been minimal and unpredictable for businesses, but attorneys still believe that is going to change.

Hacker Can Monitor Cars And Kill Their Engines After Breaking Into GPS Tracking Apps (https://motherboard.vice.com/en_us/article/zmpx4x/hacker-monitor-cars-kill-engine-gps-tracking-apps?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Motherboard | 🇺🇸 USA l April 24, 2019

A hacker broke into thousands of accounts belonging to users of two GPS tracker apps, giving him the ability to monitor the locations of tens of thousands of vehicles and even turn off the engines for some of them while they were in motion, Motherboard has learned.

Amazon's Alexa Team Can Access Users' Home Addresses (https://www.bloomberg.com/news/articles/2019-04-24/amazon-s-alexa-reviewers-can-access-customers-home-addresses?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Bloomberg | 🇺🇸 USA l April 24, 2019

An Amazon.com Inc. (https://www.bloomberg.com/quote/AMZN:US?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 ) team auditing Alexa users’ commands has access to location data and can, in some cases, easily find a customer’s home address, according to five employees familiar with the program.

Washington Legislature Passes 30-day Data Breach Notification Law (https://healthitsecurity.com/news/washington-legislature-passes-30-day-data-breach-notification-law?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Health IT Security | 🇺🇸 USA l April 24, 2019

The Washington legislature unanimously (https://app.leg.wa.gov/billsummary?BillNumber=1071&Initiative=false&Year=2019&utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 ) passed new legislation that effectively truncates the time organizations in the state must begin notifying victims of a data breach to just 30 days.

Washington State University Settles $4.7M Data Breach Lawsuit (https://healthitsecurity.com/news/washington-state-university-settles-4.7m-data-breach-lawsuit?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Health IT Security | 🇺🇸 USA l April 23, 2019

Washington State University recently settled a class-action lawsuit for $4.7 million, stemming from the 2017 data breach caused by the theft of some portable hard drives containing personal and health data.

Bodybuilding.com discloses security breach (https://www.zdnet.com/article/bodybuilding-com-discloses-security-breach/?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

ZDNet | 🇺🇸 USA l April 22, 2019

Bodybuilding.com, the internet's biggest online store and online forum for fitness and bodybuilding enthusiasts, has disclosed last week a security breach that impacted its IT systems.

60,000 Patient, Employee Records Breached in EmCare Email Hack (https://healthitsecurity.com/news/60000-patients-employee-records-breached-in-emcare-email-hack?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Health IT Security | 🇺🇸 USA l April 22, 2019

Florida-based physician-services vendor EmCare is notifying 60,000 patients, employees, and contractors that their personal data was potentially breached after a hack on several employee email accounts.

Patient PII exposed in leak of Pennsylvania-based rehab center records (https://www.cyberscoop.com/healthcare-records-leak-levittown-pa-steps-to-recovery/?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Cyberscoop | 🇺🇸 USA l April 21, 2019

A trove of personally identifiable information on patients at an addiction treatment center in Pennsylvania has been left in an insecure database, potentially exposing those people to identity theft.

Zuckerberg could be held personally accountable for Facebook data breaches (https://mashable.com/article/ftc-mark-zuckerberg-facebook/?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Mashable | 🇺🇸 USA l April 19, 2019

According to a report in the Washington Post (https://www.washingtonpost.com/technology/2019/04/19/federal-investigation-facebook-could-hold-mark-zuckerberg-accountable-privacy-sources-say/?noredirect&utm_term=.323736e04979&utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 ) , the Federal Trade Commission (FTC) is currently investigating Facebook and looking into whether the Facebook’s founder and CEO should be held liable for the company’s data mishandling and privacy issues.

Iranian Ride-Hailing App Database Exposure (https://securitydiscovery.com/iranian-ride-hailing-app-database-exposure/?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Security Discovery | 🌎 UK l April 18, 2019

On April 18th, during our regular security audit of nonSql databases with BinaryEdge search engine, I have discovered an open and publicly available MongoDB instance which contained astonishingly sensitive information on Iranian drivers.

Facebook now says its password leak affected ‘millions’ of Instagram users (https://techcrunch.com/2019/04/18/instagram-password-leak-millions/?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

TechCrunch | 🇺🇸 USA l April 18, 2019

Facebook  (https://crunchbase.com/organization/facebook?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )  has confirmed its password-related security incident last month (https://techcrunch.com/2019/03/21/facebook-plaintext-passwords/?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 ) now affects “millions” of Instagram users, not “tens of thousands” as first thought.

SOCIAL MEDIA

Screenshot 2019-04-24 at 6.41.25 PM (https://twitter.com/zackwhittaker/status/1120042096776421381?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

Screenshot 2019-04-24 at 6.56.03 PM (https://twitter.com/ericgeller/status/1121171963764932609?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

twitter (https://www.twitter.com/UpGuard?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

linkedin (https://www.linkedin.com/company/upguard/?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

facebook (https://www.facebook.com/UpGuard?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

SUGGESTIONS

That's all we have for this week's newsletter! If you have any thoughts, please just reply and drop me a line. See you next week.

Forwarded this email? Subscribe to the week in breaches (https://www.upguard.com/blog/subscribe?utm_source=hs_email&utm_medium=email&utm_content=72069587&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

UpGuard Inc.

723 N Shoreline Boulevard

Mountain View

CA

94043

United States

You received this email because you are subscribed to All Emails
from UpGuard Inc..

Update your email preferences (https://www.upguard.com/hs/manage-preferences/unsubscribe?d=VnzSxw93qYDGW49KwbH4r48VdW41-F3c1VnqjfW3z9DSW21pgssW4rDLVZ1YZ-8VW1XqJ6S4kBrC-W3QZQ9t3M4TcQW2m8Bdx3-1rV9W3T3R4J3BKSWwW3_fT6q6hnTxVVmWFdH7yXzPrN6dXYv125BqTW62YvLJ5N2NhZVWGjzy5km-gqMXk_7QbvXscW1gSmnY8d3X38W8g46X72_6flM371N2&v=3&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )
to choose the types of emails you receive.

Unsubscribe from all future emails (https://www.upguard.com/hs/manage-preferences/unsubscribe-all?d=VnzSxw93qYDGW49KwbH4r48VdW41-F3c1VnqjfW3z9DSW21pgssW4rDLVZ1YZ-8VW1XqJ6S4kBrC-W3QZQ9t3M4TcQW2m8Bdx3-1rV9W3T3R4J3BKSWwW3_fT6q6hnTxVVmWFdH7yXzPrN6dXYv125BqTW62YvLJ5N2NhZVWGjzy5km-gqMXk_7QbvXscW1gSmnY8d3X38W8g46X72_6flM371N2&v=3&_hsenc=p2ANqtz-_y4_nofV2ZOkMJ4RdSMO-kl6bCTT1J-Y9CISl3ii04V3N5d-0pT9QWsplCnfYKNU1dBlXDbXRJMP2gFJE5cAMr3hVQfofOYnYI00O-EYMSQfLRHd67qZ8_RaM0V9rRvrH0rQkcpUZhnLvssHC2ngTivgi4EQ&_hsmi=72069587 )

**Comment by toomuchmunsch** [comment]
UpGuard has been nominated for Cyber Risk Pre-Breach Team of the Year. Vote before Friday to support our team!

UpGuard (http://upguard.com/?utm_source=hs_email&utm_medium=email&utm_content=72084386&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 )

Hi there,

We are honored to announce that we have been shortlisted as a nominee for the Advisen 2019 Cyber Risk Awards. UpGuard has been nominated for the Cyber Risk Pre-Breach Team of the Year.

Cyber Risk Pre-Breach Team of the Year: Practice makes perfect... There is huge value in preparing for the worst, and making your best defense into offense in the face of an incident. This award will honor a cybersecurity consultancy team or corporation that has successfully prepared and mitigated loss pre-breach.

Our team has been recognized for the work we have done to mitigate risks pre-breach through our efforts to secure data exposures. You have likely seen our success discovering and securing exposed data for entities such as Facebook and Cultura Colectiva (https://www.upguard.com/breaches/facebook-user-data-leak?utm_source=hs_email&utm_medium=email&utm_content=72084386&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 ) , Viacom (https://www.upguard.com/breaches/cloud-leak-viacom?utm_source=hs_email&utm_medium=email&utm_content=72084386&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 ) , Level One Robotics (https://www.upguard.com/breaches/short-circuit-how-a-robotics-vendor-exposed-confidential-data-for-major-manufacturing-companies?utm_source=hs_email&utm_medium=email&utm_content=72084386&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 ) , LocalBlox (https://www.upguard.com/breaches/s3-localblox?utm_source=hs_email&utm_medium=email&utm_content=72084386&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 ) , Octoly (https://www.upguard.com/breaches/cloud-leak-octoly?utm_source=hs_email&utm_medium=email&utm_content=72084386&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 ) , and many more (https://www.upguard.com/breaches?utm_source=hs_email&utm_medium=email&utm_content=72084386&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 ) . By performing researching and developing technology to detect live data leaks, we are able to secure data exposures before those with malicious intent gain access to the information.

We would greatly appreciate your support in showing your recognition of these efforts by voting for our team.

Voting ends Friday, April 26 at 11:45pm ET

Vote Now (https://cta-image-cms2.hubspot.com/ctas/v2/public/cs/ci/?pg=1feede5a-742a-4a73-afb1-2ad1abed08dc&pid=228391&ecid=ACsprvvRkH_VwEkCd5DMhw-cSRQgaTIvpG-FUjIFDTpc0HewGmoQloYf3IMwXmGHFosOIZAZoDtI&hseid=72084386&hsic=false&utm_rewrite=REWRITE_ALL&utm_source=hs_email&utm_medium=email&utm_content=72084386&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 )

Sincerely,

Kelly

UpGuard Inc.

723 N Shoreline Boulevard

Mountain View

CA

94043

United States

You received this email because you are subscribed to All Emails
from UpGuard Inc..

Update your email preferences (https://www.upguard.com/hs/manage-preferences/unsubscribe?d=VnzSxw93qYDGW49KwbH4r48VdW41-F3c1VnqjfW3z9DSW21pgssW4rDLVZ1YZ-8VW1XqJ6S4kBrC-W3QZQ9t3M4TcQW2m8Bdx3-1rV9W3T3R4J3BKSWwW3_fT6q6hnTxVVmWFd887lfXvN8t4ZTg25zFpW5kHV9G55QB7ZVWVQS566N_lvMXk_7QbwdskW1Ht9c46Z40sVW15G8Dn6_fbbV37tt2&v=3&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 )
to choose the types of emails you receive.

Unsubscribe from all future emails (https://www.upguard.com/hs/manage-preferences/unsubscribe-all?d=VnzSxw93qYDGW49KwbH4r48VdW41-F3c1VnqjfW3z9DSW21pgssW4rDLVZ1YZ-8VW1XqJ6S4kBrC-W3QZQ9t3M4TcQW2m8Bdx3-1rV9W3T3R4J3BKSWwW3_fT6q6hnTxVVmWFd887lfXvN8t4ZTg25zFpW5kHV9G55QB7ZVWVQS566N_lvMXk_7QbwdskW1Ht9c46Z40sVW15G8Dn6_fbbV37tt2&v=3&_hsenc=p2ANqtz--WMnqQyAoTDvFEB2hztMU0ln7jzSiSUvgO8-nDg49jEMtGYMTgaf_mnsQklog8yJFNHTuUazK96bSz1yppjegPwLjK5DkAdY4_kOU-3mtHWLFBjwTRyMx-Ro1IXCC_lQieG1R8wkkDiw1KldM0Z24VZ9bLZA&_hsmi=72084386 )

**Comment by mattifestation** [comment]
@toomuchmunsch Can you please send your spam in the form of a pull request?
